export enum MessageModalType {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  MULTISIG_SUCCESS = 'MULTISIG_SUCCESS',
  EXPORT_TRANSACTIONS_SUCCESS = 'EXPORT_TRANSACTIONS_SUCCESS',
  EXPORT_TRANSACTIONS_ERROR = 'EXPORT_TRANSACTIONS_ERROR',
}
  