require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'mobileKeychain' do
  config = use_native_modules!
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  use_frameworks! :linkage => :static
  setup_permissions(['Camera'])
  use_react_native!(:path => config["reactNativePath"])
 


  target 'mobileKeychainTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

